### ISSUE TITLE
Automate the installation of the system

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#109]
## Describe the New Feature ##
Create an automated process for new users to install the system on their own AWS account. Idea is to create a series of questions the new user can answer and then everything is setup behind the scenes.

- [ ] Create CloudShell bootstrap script 
    - [x] Install Python3.9
    - [x] NodeJS 16
    - [x] Angular 14
    - [x] WRF Cloud Build Artifact - lambda layer code
    - [x] WRF Cloud Build Artifact - lambda function code
    - [x] WRF Cloud Build Artifact - web application bundle
    - [x] Install wrfcloud Python package
    - [x] Run wrfcloud-setup command

- [ ] WRF Cloud Setup Command
    - [x] Get user input values:
        - [x] Web application host name and domain
        - [x] API host name and domain
        - [x] Websocket host name and domain
        - [x] Admin user email address and new password
    - [ ] Create Image Builder Stack
    - [ ] Trigger build in the image builder pipeline
    - [ ] Create CloudFormation Data Stack
    - [ ] Create CloudFormation Certificate Stack
    - [ ] Validate Certificates via DNS / Route53
    - [ ] Create CloudFormation Web Application stack (needs lambda layer and zip files)
    - [ ] Validate SES identity
    - [ ] Create admin user

- [ ] Document steps
- [ ] Test steps

Information needed from user:

- web domain name
- initial model config info e.g. config name, namelists, geo_em files.

### Acceptance Testing ###
New user should be able to setup and install system.

### Time Estimate ###
5 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
