### ISSUE TITLE
Create new model configuration on UI

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#112]
## Describe the New Feature ##
Users need to be able to create a new model configuration on the UI. The first step is to create a feature allowing the user to upload namelists to create new configuration. Work done in #111 will then take these and run geogrid to create and upload new geo_em files to S3. 

- [ ] **Add namelist upload and configuration options to UI**
   - Input required from user:
        - namelist.wps
        - namelist.input
        - config name
        - core option (if not default of 96)

- [ ] **Make config name dynamic on backend**
   - Change of config name "test" was hardcoded on website for purposes of AGU. This needs to be automated on backend.

- [ ] **Add new "maintainer" role**
   - This role is between regular and admin and will have permissions to create these new model configurations

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Need to consider nprocs setting when adding new configuration.
e.g. in test.yml
settings:
    queue: debug
    wrfcores: 96
