### ISSUE TITLE
Add popup functionality to control job actions on the `WRF Jobs` UI tab

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/wrfcloud#139]
## Describe the New Feature ##
This task is to enhance the functionality on the `WRF Jobs` tab of the UI to make it consistent with the existing functionality on the `Manage Users` tab. When you click on a line for one of the jobs, launch a new popup window to provide details about the job.

- Recommend reporting the status of the job as "Submitted", "Running", or "Complete". Or refine them as needed to make them simple from a technical perspective while also meaningful to users.
- For "Submitted" or "Running" jobs, recommend supporting an action to "Cancel" the job.
- For "Complete" jobs, recommend supporting actions to "Open Viewer" and "Delete".

### Acceptance Testing ###
Recommend having an independent person carefully test the new functionality added to the corresponding PR.

### Time Estimate ###
*Estimate the amount of work required here.*
@hahnd should estimate this.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @hahnd
- [x] Select **scientist(s)** or **no scientist** required: @fossell

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
