### ISSUE TITLE
Improve UI error message to validate user-defined configuration names

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/wrfcloud#140]
## Describe the Enhancement ##
On the `Run WRF` tab, the user-defined optional `Job Name` cannot contain embedded whitespace, along with other special characters. However, the UI allows me to submit a job containing whitespace. Although the corresponding job just hangs with status = `Launching Cluster`.

![bad_name](https://user-images.githubusercontent.com/21087144/218547998-8d29499b-1759-4f00-aae9-8553fe7a2543.png)

![status](https://user-images.githubusercontent.com/21087144/218548019-e5bdc04d-e866-4068-9e7c-97ab81bb7706.png)

This task is to add a validation step to the UI to prevent jobs with invalid job names from being submitted. It should provide a popup error message to tell the user which characters are valid.

### Time Estimate ###
*Estimate the amount of work required here.*
@hahnd should estimate this.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required - not needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hahnd** [comment]
@JohnHalleyGotway - The Job Name on this screen allows free form text.  It should be the Name field when you create a new Model Configuration that is restricted.  Here's a video of the fix for that.  It's also live on wrfcloud.com right now.  Will submit a PR, unless this was a different issue you found.

https://user-images.githubusercontent.com/7718310/219466482-1d4b8eba-680f-44aa-9e8c-d9e683f67698.mov
