### ISSUE TITLE
Create Version 1.0 Release

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#153]
## Describe the Task ##
This task provides final checklist of tasks for finalizing the release of Version 1.0 (see [milestone](https://github.com/NCAR/wrfcloud/milestone/3) for details). 

**Initiate release:**
- [x] Define scope for pre-release testing and document below
- [x] Draft Release Page
- [x] Clean up AWS account, feature branches, etc.
- [x] Update UG release page with notes

**RC1 Pre-release Testing:** Week of March 27
- [x] Create release branch: release_v1 - March 28
- [x] Create release candidate tag: v1.0.0_rc1 - March 28
- [x] Installation (Paul) - March 29
- [x] Several variants of UI Forecasts (TBD) - March 30-31

**RCx Pre-release Testing:** (if needed)
- [ ] Create tag: v1.0.0_rcx

**Finalize release:**
- [x] Review public website content, update as necessary (check disclaimer links)
- [x] Merge release branch to develop
- [x] Merge release branch to main
- [x] Create final official release tag from main branch: v1.0.0
- [x] Trigger release RTD documentation: release version (from release tag) and stable (from main branch) labels)
- [x] Update & Publish Release Page
- [x] Work with UCAR Media if desired - N/A this release

### Time Estimate ###
1 week

### Relevant Deadlines ###
March 31, 2023

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
