### ISSUE TITLE
Create Version 1.1 Release

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#189]
## Describe the Task ##
This task provides final checklist of tasks for finalizing the release of Version 1.1 (see [milestone](https://github.com/NCAR/wrfcloud/milestone/4) for details). 

**Initiate release:**
- [x] Define scope for pre-release testing and document below
- [x] Draft Release Page
- [x] Clean up AWS account, feature branches, etc.
- [x] Update UG release page with notes

**RC1 Pre-release Testing:** 
- [x] Create release branch: release_v1.1
- [x] “pip freeze” on release branch and main branch to freeze versions of dependencies. 
- [x] Create release candidate tag: v1.1.0_rc1
- [x] Reinstall system
- [x] Several variants of UI Forecasts (TBD)

**RCx Pre-release Testing:** (if needed)
- [ ] Create tag: v1.X.0_rcx

**Finalize release:**
- [x] Review public website content, update as necessary (check disclaimer links)
- [x] Edit versions in appropriate places (Line 5 of setup.py -- now edit VERSION and RELEASE_DATE in python/src/wrfcloud)
- [ ] Merge release branch to develop - Need to do an additional PR/commit to develop change frozen versions
- [x] Merge release branch to main
- [x] Create final official release tag from main branch: v1.1.0
- [x] Check RTD documentation: release version (from release tag) and stable (from main branch) labels)
- [x] Update & Publish Release Page

### Time Estimate ###
1 week

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
July 14, 2023

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
@hahnd - The release has been published and v1.1.0 tagged. Please proceed with the reinstall and testing for the release. Thanks!

**Comment by hahnd** [comment]
The system was re-installed and I completed a successful model run:
https://app.wrfcloud.com/view/W8E1721A1F6

**Comment by fossell** [comment]
@hahnd - Great thanks!
