### ISSUE TITLE
Enhance UI to allow users to easily view the log files

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#198]
## Describe the New Feature ##
As an enhancement to error checking and logging from #26/#197, add ability to view the log output / error message directly on the UI to reduce need to login to AWS and download full log files. 

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
Unsure , 2-3 days?

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
v1.1 release

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [X] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
@georgemccabe - New issue for displaying log/error messages in UI. Please scope out the issue as necessary.
