### ISSUE TITLE
Add documentation for job status display in UI

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#200]
## Describe the Task ##
Per Issue #26 / PR #197, new error checking is enabled that displays failure messages to the UI. User guide needs to be updated to include description of these status messages. currently thinking this should be added to UG 4.4.1, with mention of next steps to advanced debugging by accessing full logs in S3 (currently described in UG 3.3). 

Information from PR #197:

> Failures from each process are caught and reported to UI.
> Status message displayed on UI for a failed job will include the process name, e.g. GeoGrid failed, if the process returned a non-zero error code, if none of the expected output files exist, or if the log file does not contain text that signifies a successful run. If something else goes wrong in the run logic, the status message will just say Failed.

Holding off on doing this right now in light of planned feature #198 to also display details of log files directly in the UI. With this development, documentation in UG will change or be added to. 

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Merging this issue with #220.
