### ISSUE TITLE
Change color bar of precip accum 

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#214]
## Describe the Enhancement ##
Request from Paul: The brown for low precip accumulations is distracting, can the precipitation accumulation colorbar be switched to the precipitable water colorbar? 

### Time Estimate ###
2 hours w/ testing

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
June 30, 2023

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
@hahnd, @georgemccabe, - I think this is a simple request to change and test. Would it just mean changing `BrBG` to `viridis` for precip accummulation in the yaml file [here](https://github.com/NCAR/wrfcloud/blob/5a3d74a08a3ca2f75e6f733fe51b2af5f665e64a/python/src/wrfcloud/runtime/resources/geojson_products.yaml#L85). Right?
