### ISSUE TITLE
Latest Available Cycle

### ISSUE THREAD

**Issue by hahnd** [NCAR/wrfcloud#235]
## Describe the New Feature ##
In the Launch WRF user interface, add an option to select the "Latest Available Cycle Time" rather than manually selecting the date and cycle.  The server-side could search for the latest available IC/BC data at runtime.

### Time Estimate ###
24h

### Tasks ###
- [ ] Update the UI to include a check box for the "Latest Available Cycle Time" -- when selected, the date/cycle hour selections should either be disabled or not displayed.
- [ ] Update the API request data structure to include a representation for latest available.
- [ ] Create a Python function to find the latest cycle time of the IC/BC data set.
- [ ] Update the Python function that runs WRF and creates the namelist to call the function to get the latest cycle time if that option is set in the request.  Start with RunWrf action in the API.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
