### ISSUE TITLE
Improve error handling for NWP components

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#26]
## Describe the New Feature ##
Need to add error handling to check that the ungrib and metgrid programs ran succesfully.
Example from David:
exit_code = os.system(metgrid_cmd) 
if exit_code == 1: 
   logger.error('Metgrid failed because ...') 
elif exit_code == 2: 
   logger.error('Metgrid failed because ...') 
elif exit_code != 0:
   logger.error('Metgrid failed for an unknown reason.')

Unsure if there are standard errors from these programs.  Additional considerations:
- could also check for "Success" or "ERROR" in log file? 
- Check that output files exist and are non-zero

Parse the log files from S3 to display error messages on UI.

### Acceptance Testing ###
Need to test successful runs and force failures to test error codes. Simply moving a required input file, e.g. geo_em.d01.nc or executable would be sufficient for basic tests.

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by mkavulich** [comment]
@hahnd I hope this is a good summary of your recommendations from our conversation today, let me know if you have any corrections or comments.

Per our discussion at today's meeting, the best path forward seems to be twofold:

1. Modify the existing "log.fatal" functionality to raise the appropriate exceptions alongside helpful log messages for identifying the exact failure that has occurred.
2. Trap exceptions (using [Python's `try` functionality](https://docs.python.org/3/tutorial/errors.html)) within the various subprocesses and simply indicate a specific task's success by returning True or False. Then the exceptions can be handled appropriately (and potentially a non-trapped exception raised) at the "Process" level (run.py).

Some specific areas that need error handling:

 - [ ] Existing custom exceptions should be modified to use the above approach
 - [ ] Compiled executables should be checked for non-zero exit status to indicate failure. However, even if the exit status is zero, this can not always be trusted, so...
 - [ ] we should set up custom error-checking functions to be run after each executable completes to check the log and output for known error conditions
 - [ ] Data-retrieval from NOMADS can seemingly hang if the internet is unavailable, need a quicker timeout
 - [ ] Add others as you notice them!

**Comment by fossell** [comment]
@hahn - Below are the minimum files to check for to determine if it's likely the component completed successfully. In other workflows, this boils down to a simple check in csh, e.g. `if ( -e $filename )` and `if ( -z $filename) ` and then grepping of text in the log files, e.g. if ( `grep "wrf: SUCCESS COMPLETE WRF" ./rsl.out.0000 | wc -l`  != 0 ) touch -f ./wrf_mem${mem}_done . There's probably something simpler to implement in the python code. 

It would make sense to add these checks in each component and feed back a notice to the user about where it failed and where to find the log files in S3 to search for the errors. In some cases, there could be file for each domain, denoted with d0*, or multiple files with various date/time strings appended. For our cases now, we only have one domain. I put an example of a full filename for each of these for reference.  Checking for files with date/time stamps might be more involved, we're not really tracking that in anyway.  We could parse the namelist to get the final expected date/time and search for that file, in addition to success text?

**Geogrid**
Files output: geo_em.d0*.nc  (geo_em.d01.nc)
Success text in geogrid.log: “Successful completion of program geogrid.exe”

**Ungrib**
Files output: FILE* (FILE:2023-03-09_12)
Success text in ungrib.log: “Successful completion of program ungrib.exe”

**Metgrid**
Files output: met_em.d0*.nc (met_em.d01.2023-03-09_12:00:00.nc)
Success text in metgrid.log: “Successful completion of program metgrid.exe”

**Real**
Files output: wrfbdy_d01, wrfinput_d0* (wrfinput_d01)
Success text in rsl.out.000: “SUCCESS COMPLETE REAL_EM INIT”

**WRF**
Files output: wrfout_d0* (wrfout_d01_2023-03-09_12:00:00)
Success text in rsl.out.0000: “SUCCESS COMPLETE WRF”

**Comment by fossell** [comment]
For error handling, I'll have to think of some common failures that may occur and document how to grep for those errors. Generally we could search for FATAL in rsl* files, but there are other error/fatal messages that could occur. One example we encountered before is below:

Scenario: when the number of cores selected is way too large for the domain, the error message in the **real** component in `rsl.out.0000` looks like this:
```
taskid: 0 hostname: r7i1n32
 Ntasks in X           12 , ntasks in Y           12
  Domain # 1: dx =  4000.000 m
   For domain            1 , the domain size is too small for this many processors, or the decomposition aspect ratio is poor.
   Minimum decomposed computational patch size, either x-dir or y-dir, is 10 grid cells.
  e_we =   100, nproc_x =   12, with cell width in x-direction =    8
  e_sn =   100, nproc_y =   12, with cell width in y-direction =    8
  --- ERROR: Reduce the MPI rank count, or redistribute the tasks.
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    2766
NOTE:       1 namelist settings are wrong. Please check and reset these options
-------------------------------------------
```
