### ISSUE TITLE
Build out real.py and wrf.py to run the corresponding programs

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#32]
## Describe the Enhancement ##
The skeleton scripts for real.py and wrf.py need to be expanded to actually execute those programs. Requires development of tools/make_wrf_namelist.py as well as generating job scripts (slurm on wrfcloud cluster, but could have PBS too for Cheyenne testing?).  

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] Create tools/make_wrf_namelist.py
- [ ] Add functions to real.py to execute real.exe
- [ ] Add functions to wrf.py to execute wrf.exe

### Relevant Deadlines ###
30 August 2022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
