### ISSUE TITLE
Add UPP for post-processing

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#34]
## Describe the New Feature ##
Some of the desired forecast products will require a post-processing package since they cannot be output by WRF. UPP provides these diagnostics and will also make the incorporation of MET verification easy, since it works well with UPP's grib2 output.  

### Acceptance Testing ###
UPP will read in WRF netcdf output files.
Tests required will include:
- Confirming UPP image is built with Imagebuilder
- Testing a new run_upp.py script to run UPP on the WRF output files

### Time Estimate ###
1 week total

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] #50  (need assistance from engineer)
- [x] #51  (scientist)

### Relevant Deadlines ###
September 30, 2022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Closed with #52  and #81
