### ISSUE TITLE
Document list of forecast products

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#38]
## Describe the Task ##
Need to identify a list of products that will be available for display for each of the forecasts. First work offline with team to collect all potential products and necessary data information. Then finalize the list and include in the documentation.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Work offline on [doc](https://docs.google.com/document/d/1zGFmjZk0aBCRm8APGMZg8txfAaFQH_bH_yK14Grzj8k/edit) to identify all potential products and information
- [x] Finalize the list for beta version
- [x] Include list in the documentation

### Relevant Deadlines ###
Sep 30, 2022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Initial set of products has been implemented and documented in the users guide.
