### ISSUE TITLE
Document S3 archive structure

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#39]
## Describe the Task ##
S3 will be used to store static input files as well as archiving forecast data. Need to document the directory structure and naming conventions of the S3 space.  

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] Work offline on [doc](https://docs.google.com/document/d/1mbvAn0KdA6og9wY8REkhnNm4HkH5f5BeKeAUcusuDL0/edit) to finalize the organization
- [ ] Add documentation reflecting the directory structure and naming conventions

### Relevant Deadlines ###
Sep 30, 2022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
