### ISSUE TITLE
Test and Evaluate different WRF configurations

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#40]
## Describe the Task ##
CIMH produces 4 different forecasts [domains](http://nmm.cimh.edu.bb/#/), each in a different geographical region and different resolution (12km or 4km). Use these to generate data for different domains and cases to be used later for comparisons. Resources on Cheyenne allow us to run numerous cases now and archive the data for further evaluation later.  

Experiments to run:
1. 4 domains
2. 5th domain that'a union of all 4 (if time/resources allow)
3. For each domain, 1-2 high impact events and 1 week (or more, if time/resources allow) period of 00z initializations

Goals for running this experiments:
1. Evaluate configurations against observations offline
4. Compare against CIMH baselines
5. Demonstrate verification capabilities
6. Can help inform implementation of verification components

### Time Estimate ###
1 month

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] Generate data
- [ ] Compare to original CIMH domains
- [ ] Implement verification components 

### Relevant Deadlines ###
Data needs to be generated by Sep 30, 2022 since compute resources expire.
Entire evaluation will take longer. 

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
