### ISSUE TITLE
Pull static domain files (geo_em.d0*.nc) from S3 to cluster

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#44]
## Describe the New Feature ##
The geo_em.d0*.nc files will be stored in the organization's S3 bucket. Need code to copy these files onto the cluster when running a forecast. The current scripts expect these files to be in wrfcloud/runtime/domains/_[expn_name]_/geo_em.d0*.nc. Presumably on the cluster this will be something like /data/wrfcloud/runtime/domains/_[expn_name]_/geo_em.d0*.nc. 
* Note: The name "domains" in the paths will likely change per Issue #23 and PR #33.
* Note: The organization of S3 bucket is being handled in #39  

### Acceptance Testing ###
Test to confirm geo_em.d0*.nc files are successfully pulled from S3 and the "test" case can run.  

### Time Estimate ###
2-3 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Aug 30, 2022

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Use boto3 libraries to pull files from S3 to cluster. Example [here](https://github.com/NCAR/wrfcloud/blob/43ada33357b818409c0bd941678bbc8e40130ce4/python/src/wrfcloud/api/actions/wrf.py#L242)

**Comment by fossell** [comment]
Add geogrid.py to runtime that initially just copies existing geo_em.d01.nc file from S3 to cluster. For future, user can run geogrid.exe to create their own.

Make a class with create, read, update, delete function for geo_em.d0*.nc.

**Comment by fossell** [comment]
Bucket name has to be unique, pass this in as environment variable via yaml file to cluster.
Env vars get set in Lamda function, e.g. wrfcloud-input-493fd7ks.    Or in repo, wrfcloud/setup/ aws/cf_wrfcloud_webapp.yaml - LambdaFunction

**Comment by fossell** [comment]
This issue evolved and is being handled in other more relevant issues. Closing.
