### ISSUE TITLE
Geojson Layers

### ISSUE THREAD

**Issue by hahnd** [NCAR/wrfcloud#49]
## Describe the New Feature ##
Add capability to display and animate GeoJSON layers in the web application:
 - [x] Generate a set of GeoJSON variables and upload to S3 bucket following the [documented data structure](https://docs.google.com/document/d/1mbvAn0KdA6og9wY8REkhnNm4HkH5f5BeKeAUcusuDL0/edit).
 - [x] Update API to get a list of model _configurations_.
 - [x] Update API to get a list of _model run times_ for a given _configuration_ name.
 - [x] Update API to get a list of _valid times_ for a given _model run time_.
 - [x] Update API to get GeoJSON data given a _configuration_ name,  _model run time_, valid time, and variable name.
 - [x] Update UI to query available model _configurations_.
 - [x] Update UI to query available _model run times_ given a _configuration_ name.
 - [x] Update UI to query available _valid times_ given a _configuration_ name and a _model run time_.
 - [x] Update UI to request and display GeoJSON data.

### Acceptance Testing ###
WRF output data are displayed with a nice user experience.

### Time Estimate ###
3d

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Fixed with #56
