### ISSUE TITLE
Shift to using log.py only for logging messages

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#53]
## Describe the Enhancement ##
There are currently two different methods for logging used by the system: 1) [log.py](https://github.com/NCAR/wrfcloud/blob/develop/python/src/wrfcloud/log.py) built by @hahnd, and 2) Python logging module implemented by @mkavulich for WRF run scripts.  It was decided it would be best to only use one, and that we should use (1) log.py given that it can log in json format allowing for integration with Cloudwatch, it's customizable, and provides better format for stack tracebacks and exception messaging.  

@hahnd will update the runtime package to use log.py, using ungrib.py as an example, and also enhance it with an UI log option to send messages to the user for viewing on the website.

- [ ] Make log parameters members of a class to pass around
- [ ] Use log.py module instead of internal python logging
- [ ] Add UI log option

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
30 August, 2022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hahnd** [comment]
@fossell - I'm going to hold off on this task until #33 is merged.  That PR has several changes to ungrib.py, metgrid.py, run.py.  I want to avoid merge conflicts on those files.

**Comment by fossell** [comment]
@hahnd - Makes sense, no problem I'll try to move #33 along and get it merged.
