### ISSUE TITLE
Run WRF API Action

### ISSUE THREAD

**Issue by hahnd** [NCAR/wrfcloud#57]
## Describe the New Feature ##
The API should have a new action to run WRF:
- [ ] Create a new action class to run WRF
- [ ] Update pcluster file to run a CustomAction OnNodeConfigured with a fake action to log back to UI and terminates the cluster
- [x] Update pcluster code to find latest AMI in the account
- [ ] Grant permission to Lambda function to create cluster
- [ ] Grant permission to the cluster to destroy itself

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] Modify create_cluster to use unique name with ref_id (David)
- [x] Modify create_cluster to run a custom command when ready (David)
- [ ] Add checking of UI parameters in RunWRF action (Mike)
- [x] Create run.yml file in RunWRF action with UI passed params ( ? )

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
David put the subtasks for cluster_create into [feature-57/run_wrf_api](https://github.com/NCAR/wrfcloud/tree/feature-57/run_wrf_api) branch. 
Kate is taking the branch from there and adding procedures to create the test.yml, copy namelists and geo_em files from S3 in this action as well.
Mike is still going to look at the validation of user params.
