### ISSUE TITLE
Identify list of parameters needed from user

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#63]
## Describe the Task ##
Need a list of parameters that scripts expect to get from user. 

### Time Estimate ###
1 hour group discussion

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Current list of parameters along with lower/upper bounds includes:

1. **start date**: Feb 11, 2021 - Current date (? smart enough to determine if data will be available for current cycle)
2. **end date**: startdate+384 hours
3. **output frequency**: 60min - 384hours
4. **input frequency**: 3 hourly (restricted to available data)
5. **CPU specs**: depends on domain configuration, but needs to be passed to run scripts
6. **config name**: along with this name comes a set of parameters that remain static for that configuration. where are these stored/defined? Need them to fill in namelists, or need hard coded nameslist associated with each configuration.
