### ISSUE TITLE
Select namelist parameters on UI to create namelists on demand

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#64]
## Describe the New Feature ##
This represents the larger vision of having the user able to select their own domain parameters via the UI. Issue #111 will handle running geogrid and uploading to S3. This issue should handle enhancing the UI to select these parameters, passing them through the api to the runtime module to create the namelist on the fly and run geogrid.

Information needed from the user for the namelist.wps should be limited to:

1.  max_dom 
2.  parent_id     
3.  parent_grid_ratio 
4.  i_parent_start
5.  j_parent_start
6.  e_we
7.  e_sn
8.  geog_data_res 
9.  dx
10.  dy
11.  map_proj 
12.  ref_lat   
13.  ref_lon  
14.  truelat1  
15.  truelat2 
16.  stand_lon 

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] Related issue: #44 

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Related to #111 and #112

**Comment by fossell** [comment]
The scope of this issue is closed with #112.  New issue #144 will involve interactive GUI.
