### ISSUE TITLE
Consolidate runtime/tools into __init__.py

### ISSUE THREAD

**Issue by mkavulich** [NCAR/wrfcloud#70]
## Describe the Task ##
Since #60 was merged the runtime workflow is now much more object-oriented. Rather than having helper functions live in individual files in the tools/ subdirectory, it now makes more sense to gather these as methods in the Process class in the runtime __init__.py file.

### Time Estimate ###
2 hours

### Relevant Deadlines ###
September 30

### Assignee ###
- [ ] **no engineer** required
- [ ] **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
