### ISSUE TITLE
Change WPS and/or WRF settings so that initial conditions have hydrometeors

### ISSUE THREAD

**Issue by mkavulich** [NCAR/wrfcloud#77]
The current settings of WPS/WRF are such that the initial state of the model (initial wrfout files) has no hydrometeors. This greatly affects the initial forecast moisture fields, and results in unrealistic precipitation forecasts for the first several hours of the simulation (long spin-up time). This seems especially bad for a tropical setting.

## Describe the Enhancement ##
Modify the WPS or WRF settings (or both) in order to include hydrometeors in the initial conditions.

This may be as simple as modifying the VTABLE, per this wrfhelp forum post: https://forum.mmm.ucar.edu/threads/resolved-using-hydrometeor-mixing-ratios-in-gfs-metgrid-error-in-ext_pkg_write_field.8644/

There is literature that indicates this significantly reduces spin-up time (improves short-term forecasts): https://ui.adsabs.harvard.edu/abs/2020AGUFMA183.0007L/abstract

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Assignee ###
- [ ] Select **no engineer** required
- [ ] Select **scientist(s)** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
