### ISSUE TITLE
Make YAML files use a consistent suffix

### ISSUE THREAD

**Issue by mkavulich** [NCAR/wrfcloud#83]
## Describe the Enhancement ##
Currently our yaml files use a mix of `.yml` and `.yaml` suffixes. We should make this consistent.

### Time Estimate ###
2 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] Decide on `.yaml` or `.yml`
- [ ] Change relevant filenames and logic referencing those names

### Relevant Deadlines ###
NONE

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Enhancement Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
