### ISSUE TITLE
Pass input .yml configuration file from web API to WRF run process 

### ISSUE THREAD

**Issue by mkavulich** [NCAR/wrfcloud#87]
## Describe the Enhancement ##
The current code in `wrfcloud/python/src/wrfcloud/api/actions/wrf.py` takes the default test.yml file and passes it through unchanged to `wrfcloud/python/src/wrfcloud/runtime/run.py`. We need logic in `wrfcloud-cluster create` to A) check that the user inputs coming from the API are valid, and B) use those inputs to construct a run.yml file and pass it to the run process.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] Add logic to check for valid user inputs in `validate_request`
- [ ] Add logic for creating and passing YAML config file in `perform_action`

### Relevant Deadlines ###
October 14, 2022

### Assignee ###
- @mkavulich 

## Enhancement Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Note: PR #88 addresses the perform action part of this Issue.

**Comment by fossell** [comment]
Closing this issue as the tasks are already noted in #57. PR #88 takes care of the yaml file, still need to validate the parameters but there is a task on #57 for that already.
