### ISSUE TITLE
Transfer current web content to new subdomain

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#90]
## Describe the New Feature ##
Currently wrfcloud.com isn't accessible to public and it's used for our development work. We need a public place where the community can go to for information about our project, and a separate space for us to do development work and run the forecasts (i.e. login and run forecasts).

The plan is to make the current wrfcloud.com public facing with only a homepage. On that homepage we'll include a contact form and brief information about the project. **Note:** This issue only address the transfer to subdomain, not creation of homepage content (see Issue #91 for content creation).

Current website content to run/view forecasts will move to a new subdomain called app.wrfcloud.com.  So when we demo forecasts, we'll be using that subdomain, and wrfcloud.com will just serve as a public access point for project information. 

### Acceptance Testing ###
Public users should be able to access wrfcloud.com without credentials.
Development team should be able to access app.wrfcloud.com with credentials.

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
December 5, 2022 (before AGU with time to test)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
