### ISSUE TITLE
Create content for wrfcloud.com homepage

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#91]
## Describe the New Feature ##
Per Issue #90, the wrfcloud.com domain will serve as the public access point to get information about the project, with a new subdomain called app.wrfcloud.com to host all of the forecast running/viewing. 

This issue to create the content for that wrfcloud.com homepage. Content will include:

- Brief description of project
- Contact form

### Acceptance Testing ###
View wrfcloud.com and proof read content.

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
December 5, 2022 (before AGU with time to test and refine)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**

### Projects and Milestone ###
- [x] Select **Project**
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fossell** [comment]
Initial homepage content has been filled.
