### ISSUE TITLE
Add precip accumulation plots

### ISSUE THREAD

**Issue by fossell** [NCAR/wrfcloud#96]
## Describe the New Feature ##
UPP outputs total (runtime) accumulations, no buckets (e.g. 1-hour or 6-hour accumulations). Add code to derive these fields. To avoid too many issues with data availability, could start by automatically plotting bucket accumulation based on output frequency only. E.g. use runtime fields to compute hourly buckets if output freq is 3600sec. Create plot on GUI for these derived fields as well.

### Acceptance Testing ###
UPP grib2 output files will be used to compute these derived fields, along with output_frequency from user interface parameters.  New derived fields should contain bucket accumulations according to output frequency.

### Time Estimate ###
3-5 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] Create code for computing the derived fields
- [ ] Create plotting for the derived fields

### Relevant Deadlines ###
N/A

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**

### Projects and Milestone ###
- [ ] Select **Project**
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## New Feature Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>/<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project**, and **Development** issue
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
